### ISSUE TITLE
go-sql-driver/mysql does provide error identifiers 

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [VividCortex/go-database-sql-tutorial#104]
Hi!
First of all, amzing tutorial. Thank you very much.

In the [Error section](http://go-database-sql.org/errors.html) of the tutorial you say:
> This code is still ugly. Comparing to 1045, a magic number, is a code smell. Some drivers (though not the MySQL one, for reasons that are off-topic here) provide a list of error identifiers. 

Browsing through the [source code](https://github.com/go-sql-driver/mysql/blob/master/errors.go#L18) of the MySQL driver you use I find that they do have exported error values.

**Comment by xaprb** [comment]
Thanks! Yes, there are a few protocol-level errors that the driver exports. The server can still return many (dozens?) of other errors that aren't exported, which the VividCortex package provides. It's still a handy way to clean up magic numbers in the code!
