### ISSUE TITLE
Stored procedures and multiple resultsets

### ISSUE THREAD

**Issue by rvenugopal** [VividCortex/go-database-sql-tutorial#12]
Hi

Thanks for the excellent article.  I found it quite informative with lots of little gotchas.  Would it be possible for you to comment on the following
- Is it possible to work with multiple result sets
  If I have multiple select statements, then how can I ensure that I read each of the result sets individually?
- Invoking stored procedures and passing parameters to stored procedures
- If I include multiple statements in a transaction, does it perform a single batch i/o operation with the db or are multiple network calls made?

Thanks
-Rao

**Comment by xaprb** [comment]
I'd be interested in other contributions to this topic because I don't know
the answers.

**Comment by arnehormann** [comment]
...giving back to support my plea for the recently opened issue #15 ...

**Multiple results**: The current driver API does not support multiple result sets in any way (And there's no issue for it yet, though maybe [5171 - "database/sql: should support a way to perform bulk actions"](https://code.google.com/p/go/issues/detail?id=5171) is related).

**Invoking stored procedures**: driver specific. My answer from a [`go-sql-driver/mysql`](https://github.com/go-sql-driver/mysql) perspective is that I never used them, but it's just `CALL procedurename`, right? A regular call to `Query` or `Exec` should suffice - as long as only one result set is returned. First you have to patch the driver, though. Please read [issue 66](https://github.com/go-sql-driver/mysql/issues/66).

**Transaction IO**: As far as I know, it's one call per statement. Have a look at the [source](http://golang.org/src/pkg/database/sql/sql.go?s=24167:24236#L977).
A driver _could_ probably work around this, but I don't see any compelling reasons why it should.

**Comment by xaprb** [comment]
I've added my answers here: http://go-database-sql.org/surprises/#multiple_result_sets
