### ISSUE TITLE
Bind Variable placeholder syntax when using the Oracle driver

### ISSUE THREAD

**Issue by manangatangy** [VividCortex/go-database-sql-tutorial#13]
Hi,

thanks for this resource; it's been very useful for a golang newbie like me.
In particular, it gave me the first clue about how to fix my error, that looked
like: "sql: statement expects 0 inputs; got 1".

That clue was in the fourth paragraph of your tutorial and went like "...the most
surprising [difference] can be the need to use different syntax for placeholder
parameters in prepared statements." 

Here was I using the standard Java convention of "?" placeholder characters, when
after some investigation, it turns out that Oracle likes very different placeholders,
whose first character is a colon.  For example;
"select \* from myTable where myColumn = :a"

Since you already mention the syntax for MySQL and PostgreSQL, could
I suggest you add an example of what the Oracle syntax looks like.  
I'm sure it will be useful to someone, in the future.
## regards

David

**Comment by xaprb** [comment]
Please check the example I added. Is it correct?

**Comment by manangatangy** [comment]
Yes, that looks fine.
An unrelated problem I'm having is dealing with CLOB (character large objects) that have been stored in the database.  I can't find any information about how to select these types of columns -- do you know if they are
even supported in golang or pkg/database/sql or the oracle go driver ?
thanks

**Comment by xaprb** [comment]
I wouldn't be the right person to talk about the Oracle driver, but the database/sql package itself is fully capable of handling any datatype.
