### ISSUE TITLE
add a linkable section of frequently encountered errors

### ISSUE THREAD

**Issue by arnehormann** [VividCortex/go-database-sql-tutorial#15]
Could you help us out by adding a _linkable_ section with frequently encountered problems to the database tutorial?
I'd really love to have a bunch of short linkable answers ready when closing issues for [the mysql driver](https://github.com/go-sql-driver/mysql) - but I lack the experience in technical writing (and am not a native speaker).

What I have in mind is a way to quickly answer and close issues like
"`SELECT ?` does not work with a slice".

**Comment by xaprb** [comment]
Hmmmm... you know, we might be kind of overloading the README's capabilities. Because linkable things are going to be linked with # targets in the URL, which is not easy for you. But we could split it up and make a bunch of markdown files and serve them with github pages, which could be easier to organize. I am happy to do that -- turn a repo into a proper site, I mean. How do you feel about that?

Thank you for suggesting this, and I think it's a great idea.

**Comment by arnehormann** [comment]
I believe every header is linkable. Hover over it and it shows a link
symbol to its left, click it and you have the link. Works at least down to
h2.

Here's an example: https://github.com/VividCortex/go-database-sql-tutorial#common-database-operations

Am 22.11.2013 15:48 schrieb "Baron Schwartz" notifications@github.com:

**Comment by arnehormann** [comment]
On the other hand... having a github pages site enables granular updates and reduces merge conflicts if it takes off and more collaborators join in. And the added control over the content is probably neat, too.
Yes, I'd prefer the github-pages approach. Wouldn't have dared to suggest it myself, though...

**Comment by xaprb** [comment]
I actually have zero experience with a github pages site, but I can't
believe it is hard to do :-) I'll look into it, and any help is welcome!
I'll post on Google+ about it and see if someone wants to jump in to make
it happen, too.

**Comment by xaprb** [comment]
I've just set up a custom domain and created the site (with default content, with their auto-create tool to get started) at https://github.com/VividCortex/go-database-sql-tutorial/tree/gh-pages. The domain is go-database-sql.org. It will probably take a few minutes for this all to activate.

**Comment by arnehormann** [comment]
Great!!! :+1:

**Comment by xaprb** [comment]
It would be great to submit this to the Go Advent Calendar when it's done... https://groups.google.com/forum/#!msg/golang-nuts/UlSPVQDo-rc/jHbtK8DbxOMJ

**Comment by xaprb** [comment]
@arnehormann I've created a new team with push/pull access to this repo, and added you to that team. Feel free to make changes directly. Hooray! :)

**Comment by arnehormann** [comment]
I will definitely do so in the future - esp. extending it based on bug reports we get.
Will you (please? :grinning:) do the initial setup, basic structuring and the conversion to the github pages format?
That's actually what I'm shying away from, otherwise I'd have started with a PR and not with an issue...

**Comment by xaprb** [comment]
Hah, yeah, I'm just figuring out that Github filled my default Pages with
HTML and templates -- I thought it was all going to be Jekyll stuff by
default, so now I guess I'd better learn a little Jekyll and see if I can
get this train on the tracks again :-)

**Comment by xaprb** [comment]
http://go-database-sql.org/ is live. I've pretty much copy/pasted the current content into it. I think it needs to be restructured, but it's a start. To edit it, switch to the gh-pages branch and just modify any of the .md files.

**Comment by xaprb** [comment]
I've restructured it. I'll now look through the other contributions you added, but I'll close this issue.

**Comment by arnehormann** [comment]
Thanks!
