### ISSUE TITLE
Header too big

### ISSUE THREAD

**Issue by Preetam** [VividCortex/go-database-sql-tutorial#16]
I think the header should be smaller. It takes up over half of my screen.

![](http://i.imgur.com/HULUOXB.png)

**Comment by xaprb** [comment]
I totally agree. I just grabbed a Jekyll theme and installed it. Not an
expert. Wanna fix it or pick a different theme?

**Comment by arnehormann** [comment]
It can be fixed - but it's coded in a responsive way and depends on the resolution.
I have to confess a minor aversion to LESS, I'm still not sure I found all occurrences...

https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/assets/less/page.less#L36-L101

And maybe some more here...

https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/assets/less/variables.less#L11-L17
https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/assets/less/typography.less#L14

And then compile it for the `.min.css` file.
And hope the other headers don't look weird (I spotted a h4 declaration using rem units).

It's probably not worth the effort.

**Comment by arnehormann** [comment]
@xaprb after a little bit of searching, I stumbled over this one: https://github.com/mdo/hyde
I like it - focus on the content, enough whitespace to be easy on the eyes, mobile friendly.
Looks easily modifiable, too.
If you like it I'll try to switch (and maybe even solve issue #18 at the same time with a small modification).

**UPDATE**: I think/hope the IE 9+ restriction is not overly limiting for our target demographic...

**Comment by xaprb** [comment]
That looks nice to me. +1 and thanks :)

**Comment by xaprb** [comment]
I also just noticed this site: http://redneckbeard.github.io/gadget/ that has a theme that would probably work pretty well for this. Looks good on a browser anyway, don't know about mobile.

**Comment by xaprb** [comment]
In pull request #23 we've also been talking about using the theme that the Revel framework uses, and/or getting code block syntax highlighting somehow. Contributions are really welcomed, because I think the 3 main contributors here have little experience with this!

**Comment by arnehormann** [comment]
Header no longer too big...
