### ISSUE TITLE
"previous" and "next" navigation

### ISSUE THREAD

**Issue by julienschmidt** [VividCortex/go-database-sql-tutorial#18]
I think it would be easier to navigate through the pages if each page had "previous" and "next" links at the bottom.

Currently you have to go through the list and find the page where you currently are before clicking the link to the next page (the list item below).

**Comment by xaprb** [comment]
Good idea!

**Comment by xaprb** [comment]
@julienschmidt FYI I've added you as a collaborator to this repo.

**Comment by arnehormann** [comment]
fixed by dab7e0e7f
