### ISSUE TITLE
Does database/sql do auto-reconnects?

### ISSUE THREAD

**Issue by xaprb** [VividCortex/go-database-sql-tutorial#25]
At least with the go-sql-drivers/mysql driver, I see that I can kill database connections and continue to call stmt.Query() without any trouble. Either database/sql or the driver is catching the error from the closed connection, opening a new one, preparing a new statement, and retrying the Query() without returning an error to my code.

Which one is doing the magic? I think this should be documented.

**Comment by julienschmidt** [comment]
This is a feature of the database/sql package. As of Go 1.2 it makes up to 10 retries if the driver reports a bad connection (network error etc). But the current implementation is not 100% correct, see also http://golang.org/issue/5718 and https://codereview.appspot.com/15400044/

**Comment by julienschmidt** [comment]
Sorry, wrong CL, it meant https://codereview.appspot.com/14920046/

**Comment by xaprb** [comment]
I have been told by Brad Fitzpatrick that retries of statements on killed connections are unintentional, FWIW.
