### ISSUE TITLE
Position of defer rows.Close()

### ISSUE THREAD

**Issue by mrauh** [VividCortex/go-database-sql-tutorial#3]
In your examples, you first write "defer rows.Close()" and then you are checking for an error. If I do so and there is an error in the query, I get a panic ("panic: runtime error: invalid memory address or nil pointer dereference"). So I think the order should be reversed (first error checking, then closing):

``` go
rows, err := db.Query("select id, name from users where id = ?", 1)
if err != nil {
 log.Fatal(err)
}
defer rows.Close()
```

BTW, thanks for the nice tutorial! I wish I had something similar when I started...

Michael

**Comment by xaprb** [comment]
Someone else also pointed this out to me via email. Thanks for the issue report, both of you!
