### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by martinarrieta** [VividCortex/go-database-sql-tutorial#35]
Hello, 

The link on https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/index.md to "Overview of Go's database/sql Package" is broken :)

Thank you.

Martin.

**Comment by xaprb** [comment]
Right. Look at http://go-database-sql.org/ and the links are working. This repo is really just the source for a Github Pages website.

**Comment by arnehormann** [comment]
@xarpb I'd vote for deleting the main branch. Is there anything speaking against it?
Happy new year btw!

**Comment by xaprb** [comment]
Thanks, happy new year to you too! Good idea.
