### ISSUE TITLE
upgrade to a newer Markdown interpreter

### ISSUE THREAD

**Issue by julienschmidt** [VividCortex/go-database-sql-tutorial#45]
> Your site is using Maruku, the default Markdown interpreter. Maruku is now obsolete and may cause builds to fail for sites with invalid Markdown or HTML. See https://help.github.com/articles/migrating-your-pages-site-from-maruku for more information on upgrading to a newer Markdown interpreter. 
> 
> For information on troubleshooting Jekyll see:
> 
> https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

**Comment by xaprb** [comment]
According to the docs, we also need to rename config.yml to `_config.yml`
