### ISSUE TITLE
A word on limited concurrency

### ISSUE THREAD

**Issue by julienschmidt** [VividCortex/go-database-sql-tutorial#5]
A common problem is, that applications often reach too high concurrency at some point. This leads to too many open connections.
With the Go-MySQL-Driver this leads to `Error 1040: Too many connections` errors.

Some people confuse [DB.SetMaxIdleConns](http://golang.org/pkg/database/sql/#DB.SetMaxIdleConns) with having control over the maximum number of connections, but unfortunately in reality you have no control over it via the database/sql package: https://code.google.com/p/go/issues/detail?id=4805

It would be great if you could add a section which covers this issue and some possible solutions. For example:
- some sort of semaphore (channels)
- using async updates / caches instead

I won't have time to prepare a PR until mid. August, so I hope someone other finds a few good words on this issue ;-)

**Comment by xaprb** [comment]
Thanks for the suggestion! I'm working full-speed on something else at the
moment but will try to keep improving this tutorial fairly continuously.
Till it's perfect, that is :)

**Comment by xaprb** [comment]
By the way, I did add a link to related reading near the bottom, which
links to an external website that shows some of the things you're
mentioning.

**Comment by xaprb** [comment]
If you'd like to make a pull request for this, it would be wonderful.

**Comment by xaprb** [comment]
I've added mentions of this in various places. It should be enough for people to solve their needs, I think.
