### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by amkgo** [VividCortex/go-database-sql-tutorial#53]
The link at the end of each page is broken. 
Example: index.md
The link  to [Overview of Go's database/sql Package] should be:
https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/overview.md,  
but it's  
https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/overview.html

**Comment by xaprb** [comment]
Thanks for reporting this. Can you fix and send a pull request? Much
appreciated!

**Comment by xaprb** [comment]
Oh - this actually isn't an issue. You're looking at the code in the repo. Look at go-database-sql.org instead.

**Comment by julienschmidt** [comment]
See also #48 and #47, #49
