### ISSUE TITLE
Must update DNS settings

### ISSUE THREAD

**Issue by xaprb** [VividCortex/go-database-sql-tutorial#56]
I just got an email from Github. Copying it below...

Hi VividCortex,

The custom domain for your GitHub Pages site VividCortex/go-database-sql-tutorial needs attention. You must take immediate corrective action to ensure that your site remains available after December 1st, 2014.

Please follow the instructions for [setting up a custom domain with GitHub Pages](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/) to update your custom domain’s DNS settings to point to the proper GitHub IP addresses.

Why the change?

Nearly a year ago, we announced improvements to how we serve GitHub Pages sites. This week we’re making that change permanent by deprecating our old GitHub Pages infrastructure. If your custom domain is pointed at these legacy IPs, you’ll need to update your DNS configuration immediately to keep things running smoothly.

How long do I have to make the switch?

Starting the week of November 10th, pushing to a misconfigured site will result in a build error and you will receive an email stating that your site’s DNS is misconfigured. Your site will remain available to the public, but changes to your site will not be published until the DNS misconfiguration is resolved.

For the week of November 17th, there will be a week-long brownout for improperly configured GitHub Pages sites. If your site is pointed to a legacy IP address, you will receive a warning message that week, in place of your site’s content. Normal operation will resume at the conclusion of the brownout.

Starting December 1st, custom domains pointed to the deprecated IP addresses will no longer be served via GitHub Pages. No repository or Git data will be affected by the change.

Okay, I’m sold. What do I need to do?

Please follow the instructions for setting up a custom domain with GitHub Pages to update your custom domain’s DNS settings to point to the proper GitHub IP addresses.

Questions? We’re here to help.

Happy Publishing!

— The GitHub Pages Team

**Comment by arnehormann** [comment]
@xaprb Yeah, me too (for another repo). Apparently the IP of some front facing machine will change soon and you may need to update the DNS record of wherever go-database-sql.org (pairNIC.com?) is registered. The A record must point to the new IP.
The documentation is pretty good though. Do you need help in any way?

**Comment by xaprb** [comment]
Thanks - if you have the IP address handy already, that will save me the
trouble of looking it up!

**Comment by freeeve** [comment]
https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/#configuring-an-a-record-with-your-dns-provider

```
192.30.252.153
192.30.252.154
```

If you can't do apex A records with your dns config (some providers make it annoying), the CNAME option is easy for www...

**Comment by arnehormann** [comment]
@xaprb as @wfreeman says - and as it is configured for an apex domain now, that should not be a problem.
