### ISSUE TITLE
Explain connection state

### ISSUE THREAD

**Issue by xaprb** [VividCortex/go-database-sql-tutorial#57]
Not sure if this is adequately covered already, but in https://github.com/go-sql-driver/mysql/issues/287 someone is not aware that the queries are being run on different connections.

**Comment by arnehormann** [comment]
We explain it, but maybe we should put a stronger focus on **pool**, connection interactions and the resulting complications and less focus on resource exhaustion...
[The explanation](http://go-database-sql.org/surprises.html#connection-state-mismatch) is pretty good, but not that prominent.
