### ISSUE TITLE
Syntax for placeholder parameters

### ISSUE THREAD

**Issue by frou** [VividCortex/go-database-sql-tutorial#6]
Hi. Thanks for the useful tutorial.

When preparing a statement with placeholder parameters, both the official "database/sql" docs and your tutorial say to use question marks. Surprisingly, that causes PostgreSQL to spit a cryptic error. Turns out it wants syntax like `VALUES($1, $2, $3)` and not `VALUES(?, ?, ?)`.

I know you explicitly narrow in on MySQL up front, but as a friendlier alternative to the official docs, it would be helpful to note that  `?` isn't universal.

**Comment by xaprb** [comment]
This is a great point and brings out something that's important for people
to know: the drivers, not the database/sql package, handles the
placeholders. Can you fork and make a pull request?

**Comment by frou** [comment]
Yep, will do.
