### ISSUE TITLE
The type settings make this website generally hard to read

### ISSUE THREAD

**Issue by sibljon** [VividCortex/go-database-sql-tutorial#67]
First, thanks for the incredibly useful website.

I chose the word _might_ in the title of the Issue because I _personally_ found the website much easier to read by opening the Safari Web Inspector and using Helvetica instead of Open Sans. Looking at other examples of Open Sans on the web, it seems that there's something strange going on in this website's kerning type settings.

Obviously, feel free to close and ignore this if not useful :smile:

**Comment by arnehormann** [comment]
@sibljon could you please post a screenshot?
It looks fine to me - in Chrome, Firefox and Safari (Safari 8.0.2, OS X 10.10.1).

**Comment by sibljon** [comment]
I'm on OS X 10.10.1 as well.

Here's Chrome:
![screen shot 2015-01-19 at 9 23 12 am](https://cloud.githubusercontent.com/assets/442307/5804677/db80a5c0-9fbc-11e4-9ef5-76822eedc7b0.png)

Here's Safari:
![screen shot 2015-01-19 at 9 23 18 am](https://cloud.githubusercontent.com/assets/442307/5804682/e09b69dc-9fbc-11e4-9d1c-a1d2c834cee5.png)

Looking at my Font Book, it seems I only have the condensed versions of Open Sans on my machine:

![screen shot 2015-01-19 at 9 25 12 am](https://cloud.githubusercontent.com/assets/442307/5804721/24f7d106-9fbd-11e4-8ee3-49b7829679a2.png)

which I'm sure I can remedy on my own machine. I'll close for the time being, since it seems to be an issue on my end.

**Comment by julienschmidt** [comment]
I think the design in general could use a makeover.
I will draft something when I have a bit of free time (which might not be so soon).

**Comment by xaprb** [comment]
We could use web fonts (Google has a nice selection) to avoid some of these
kinds of problems.

**Comment by julienschmidt** [comment]
I think we already do that: https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/_includes/head.html#L8

**Comment by xaprb** [comment]
Ignore me :)
