### ISSUE TITLE
Error in sample code for fetching variable number of columns

### ISSUE THREAD

**Issue by pengux** [VividCortex/go-database-sql-tutorial#7]
When trying to run the sample code, it throws this error:

"cannot use vals (type []sql.RawBytes) as type []interface {} in function argument"

The code is:

```
    cols, err := rows.Columns()             // Get the column names; remember to check err
vals := make([]sql.RawBytes, len(cols)) // Allocate enough values
ints := make([]interface{}, len(cols))  // Make a slice of []interface{}
for i := range ints {
    vals[i] = &ints[i] // Copy references into the slice
}
for rows.Next() {
    err := rows.Scan(vals...)
    // Now you can check each element of vals for nil-ness,
    // and you can use type introspection and type assertions
    // to fetch the column into a typed variable.
}
```

**Comment by xaprb** [comment]
Thanks for reporting this! Just looking at the code, I think I'm passing
values instead of pointers, and that fix should be easy. I actually cribbed
this from the go-mysql-driver documentation, so I'll review there and
suggest any fixes needed to that documentation as well.
