### ISSUE TITLE
retrieving.md: description of rows.Close() handling doesn't match with the code

### ISSUE THREAD

**Issue by jf** [VividCortex/go-database-sql-tutorial#70]
In [Fetching Data from the Database](https://github.com/VividCortex/go-database-sql-tutorial/blob/gh-pages/retrieving.md#fetching-data-from-the-database), the explanatory text says `Notice, however, that we check the error first, and only call rows.Close() if there isn't an error, in order to avoid a runtime panic.`; but this "check error and close if no error" isn't there in the code:

```
var (
    id int
    name string
)
rows, err := db.Query("select id, name from users where id = ?", 1)
if err != nil {
    log.Fatal(err)
}
defer rows.Close()
for rows.Next() {
    err := rows.Scan(&id, &name)
    if err != nil {
        log.Fatal(err)
    }
    log.Println(id, name)
}
err = rows.Err()
if err != nil {
    log.Fatal(err)
}
```

I see only a `defer rows.Close()`. Nowhere else is `rows.Close()` called.

**Comment by arnehormann** [comment]
That is perfectly ok.
`log.Fatal` calls `os.Exit` and terminates the program - so you can think of it like `return` regarding the control flow. By deferring `rows.Close`, it is called as a last instruction when the current function terminates.
If `rows.Close` were called directly, it would have to be added before each call to `log.Fatalf` or `return`, and at the end of the function.
Defer spares you the effort and duplication - especially concerning maintenance. Without `defer`, you have to remember to call it whenever you add a new way to exit the function.

**Comment by jf** [comment]
I am aware of how `defer` works. That is not the point of this issue.

**Comment by arnehormann** [comment]
I'm sorry if I missed something, but (comments added):

``` go
rows, err := db.Query("select id, name from users where id = ?", 1)
// check error
if err != nil {
    // error, log and terminate, no Close
    log.Fatal(err)
}
// no error, Close when function ends
defer rows.Close()
```

To me, that looks exactly like `Notice, however, that we check the error first, and only call rows.Close() if there isn't an error, in order to avoid a runtime panic.`

**Comment by jf** [comment]
Ok I see. I get it now, sorry about that. I was reading that point as if it was relating to code after the `rows.Next()`. It just didn't fit in my mind that we would bring up a point about code that's _later_ (`You should always check for an error at the end of the for rows.Next() loop.`) _before_ we bring up a point about code that comes _earlier_ (ie. the `defer`). Maybe it would make more sense to rewrite or reorder the points a bit? Thanks for the added clarification.
