### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thewhitetulip** [VividCortex/go-database-sql-tutorial#78]
What license is this project released under? Will it be okay if I incorporated content form here verbatim in an open source book I am writing?

**Comment by xaprb** [comment]
Looks like we forgot to assign a license to it. There are multiple contributors so they all have to agree to any license we add now. I would be happy to use a CC license. If you can suggest one, ping all the contributors from a pull request that adds a LICENSE file, and get a thumbs up from all of us, then I will merge the pull request to make the new license official.

**Comment by julienschmidt** [comment]
I'm fine with any CC license except for the NoDerivs variants.

**Comment by thewhitetulip** [comment]
> If you can suggest one, ping all the 

Seriously? I have never contributed to the project how can I ping everyone to ask which license should be added?

**Comment by arnehormann** [comment]
I'm with Julien concerning the license.

Technically, you can ping them by looking at the [contributors](https://github.com/VividCortex/go-database-sql-tutorial/graphs/contributors) tab and by @... referencing them all in a message. Morally, it does not matter at all whether you contributed yet. This is your first contribution, then. It's a good one!

**Comment by Preetam** [comment]
Since I'm listed as a contributor, :+1: to CC.

Ping 
- [ ] @mbarb0sa
- [x] @amkgo
- [x] @hochhaus
- [x] @jmoiron
- [x] @rex64
- [x] @tpng
- [x] @razvanm
- [ ] @mikhailov
- [x] @johto
- [x] @uhoh-itsmaciek
- [x] @s7v7nislands
- [x] @perceptec
- [x] @jeteon
- [ ] @gauravagarwal

**Comment by jeteon** [comment]
CC sounds good :+1: .

**Comment by tpng** [comment]
No problem with CC :+1: , ping me again if you need another thumb up in the PR.

**Comment by perceptec** [comment]
:+1:

**Comment by johto** [comment]
CC sounds good.

**Comment by thewhitetulip** [comment]
@arnehormann hmm you do have a valid point :+1: 
But still I feel the owner/collaborators should do that right? anyways it is an individual opinion :smile:

**Comment by s7v7nislands** [comment]
:+1:

**Comment by rex64** [comment]
👍

**Comment by jmoiron** [comment]
:+1: (emoji are legally binding right)

**Comment by razvanm** [comment]
:+1:

**Comment by hochhaus** [comment]
CC approved.

**Comment by msakrejda** [comment]
Sure +1

**Comment by amkgo** [comment]
:+1:

**Comment by xaprb** [comment]
:+1:

**Comment by Preetam** [comment]
I added the [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/) license. There's also a badge on the website since the repo doesn't have a README.
