### ISSUE TITLE
Working with Unknown Columns witch has time with oracle

### ISSUE THREAD

**Issue by dfy167** [VividCortex/go-database-sql-tutorial#82]
when work with gopkg.in/rana/ora.v3 or github.com/mattn/go-oci8 
how to Working with Unknown Columns
my code
`values := make([]sql.RawBytes, len(cols))
    scans := make([]interface{}, len(cols))
    for i := range values {
        scans[i] = &values[i]
    }
    results := make(map[int]map[string]string)
    i := 0
    for query.Next() {
        if err := query.Scan(scans...); err != nil {
            fmt.Println("scan err:", err)
            return
        }
        row := make(map[string]string)
        for j, v := range values {
            key := cols[j]
            fmt.Println("xx", j, v)
            row[key] = string(v)
        }
        results[i] = row
        i++
    }`
and the error is : 
# index   TIME_STAMP

scan err: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type time.Time into type *sql.RawBytes

**Comment by Preetam** [comment]
https://golang.org/pkg/database/sql/#Rows.Scan

> Source values of type time.Time may be scanned into values of type *time.Time, *interface{}, *string, or *[]byte. When converting to the latter two, time.Format3339Nano is used.

**Comment by Preetam** [comment]
I think `*interface{}` might be a better option in this case.
