### ISSUE TITLE
empty "leftnav" ?

### ISSUE THREAD

**Issue by budui** [VividCortex/go-database-sql-tutorial#97]
I can't find nav in the website. 
Part of the HTML code:
```html

<div class="container">

   <div class="row">
   <div class="span3">
   <div class="leftnav">
   <ul class="nav nav-list">
  
 </ul>
   <hr />


```

**Comment by xaprb** [comment]
Yes, I can confirm that something appears to have broken, which used to work correctly. Perhaps it's a result of a change in GitHub pages.
